### ISSUE TITLE
这东西怎么学啊 

### ISSUE THREAD

**Issue by yulinwoniu666** [yuxitong/TensorFlowDemo#1]
model里面的代码看不懂啊兄弟

**Comment by yuxitong** [comment]
这个app里只是跑模型  跑各种模型的方法    实际上 是需要训练模型才能出现各种不同的效果  推荐你先搭个梯子看看tensorflow官网 上面有比较详细的文档

**Comment by yizhiweimengxiangfendoudefeifei** [comment]
你好，可以要个联系方式吗？我想知道这东西怎么跑起来

**Comment by yizhiweimengxiangfendoudefeifei** [comment]
在吗，可以要个联系方式吗
