### ISSUE TITLE
人脸检测好像只能是一个方向才能识别出来,其他3个方向不行

### ISSUE THREAD

**Issue by zjianflys** [yuxitong/TensorFlowDemo#11]
麻烦问一下,这个.pb 文件是怎么得来的

**Comment by yuxitong** [comment]
嗯    检测方向问题  是 因为 训练模型的时候  只采用了 正面图片训练的  没有其他方向样本 所以识别不出来         pb文件是用tensorflow  Object Detection 训练的  在github上 看tensorflow 主页 里 有源码
