### ISSUE TITLE
训练网络

### ISSUE THREAD

**Issue by someonelikeypp** [yuxitong/TensorFlowDemo#12]
请问识别出抽烟打电话闭眼睁眼的模型是用什么网络跑出来的，方便提供一下嘛，如果我要再训练的话，感谢

**Comment by yuxitong** [comment]
SSD_mobilenet

**Comment by yuxitong** [comment]
推荐你使用SSDLite  这样 运行速度更快一些   lite 和pb 的android 也几乎一样

**Comment by someonelikeypp** [comment]
谢谢~，意思是直接拿你的pb用lite框架再训练吗，训练出来的结果模型也适用你的项目是嘛；
然后方便问下你的训练集有多少吗感觉打电话的检测好像不是很准

**Comment by yuxitong** [comment]
不需要 用 config  直接训练生成模型

**Comment by someonelikeypp** [comment]
请问是用的这个config吗，ssd_mobilenet_v1_coco.config @yuxitong 
然后除了抽烟打电话闭眼睁眼其他的coco分类好像检测不出来了是什么原因呢
