### ISSUE TITLE
Do you have program  code to run on your computer (smoking and making phone calls)

### ISSUE THREAD

**Issue by wanghui6118942** [yuxitong/TensorFlowDemo#13]
thanks for your sharing！
Do you have program  code to run on your computer (smoking and making phone calls)

**Comment by yuxitong** [comment]
My automatic marking program runs on a computer.

https://github.com/yuxitong/AutoMarKingTensorFlowPython

**Comment by wanghui6118942** [comment]
忽然看到可以用中文，哈哈，就是想问下您，这个抽烟和打电话检测的在电脑phyon用的代码，您方便给一下么，我们是学校学习用

**Comment by wanghui6118942** [comment]
忽然看到可以用中文，哈哈，就是想问下您，这个抽烟和打电话检测的在电脑python用的代码，您方便给一下么，我们是学校学习用

**Comment by yuxitong** [comment]
上面那个自动打标的就是 电脑版运行的

**Comment by wanghui6118942** [comment]
谢谢您啦

**Comment by wanghui6118942** [comment]
您的那个链接只是自动打标的，是么？我们想问下您，还方不方便给一下抽烟检测和打电话检测部分的电脑版运行的程序呢？

**Comment by yuxitong** [comment]
那个打标的程序就是  电脑版运行的   只需要稍微改动一下即可。  返回的 位置信息和检测内容都有   可以自己替换成摄像头 截图 传送进去 就是电脑版了

**Comment by wanghui6118942** [comment]
偶偶，好的，麻烦您了

**Comment by wanghui6118942** [comment]
您好，程序PATH-TO-CKPT=‘frozen_inference_graph_truc_nohardexample_1028.pb ’这块没有文件，程序报错：tensorflow.python.framework.errors_impl.NotFoundError: NewRandomAccessFile failed to Create/Open: frozen_inference_graph_truc_nohardexample_1028.pb :     ϵ\udcd5Ҳ\udcbb\udcb5\udcbdָ\udcb6\udca8\udcb5\udcc4\

**Comment by wanghui6118942** [comment]
利用打标文件后遇到上述情况，您能帮忙解决下上面的问题么？

**Comment by yuxitong** [comment]
是这样的，这里面模型 需要您先自己手动打标然后训练一个版本在由此程序跑。本程序无法完全取代手动打标， 是辅助手动打标的。



这个程序存在的意义在于使用模型来跑出打标文件，然后手动修改会减少很多纯手动打标时间。




而且  随着打标越来越多模型越来越准，自动打标也会越来越准的。




------------------ 原始邮件 ------------------
发件人: "wanghui6118942"<notifications@github.com>; 
发送时间: 2019年5月26日(星期天) 晚上7:48
收件人: "yuxitong/TensorFlowAndroidDemo"<TensorFlowAndroidDemo@noreply.github.com>; 
抄送: "ごTOP灬　"<308847281@qq.com>; "State change"<state_change@noreply.github.com>; 
主题: Re: [yuxitong/TensorFlowAndroidDemo] Do you have program  code to runon your computer (smoking and making phone calls) (#13)




您好，程序PATH-TO-CKPT=‘frozen_inference_graph_truc_nohardexample_1028.pb ’这块没有文件，程序报错：tensorflow.python.framework.errors_impl.NotFoundError: NewRandomAccessFile failed to Create/Open: frozen_inference_graph_truc_nohardexample_1028.pb :     ϵ\udcd5Ҳ\udcbb\udcb5\udcbdָ\udcb6\udca8\udcb5\udcc4\

**Comment by wanghui6118942** [comment]
关于您的程序是先用这个打标文件对图片打标，然后用打标图片去训练模型是么？
现在我们学校项目想自己写出一个能识别驾驶员抽烟和打电话的程序，然后识别给定视频驾驶员的驾驶行为。您现在的程序里包括已经训练好的模型么（不需要自己在进行训练和图片打标，我们只是学交通专业的，所以对这方面不太懂），是可以直接进行识别的么？如果有的话，您方便提供一下么？
实在是麻烦您了！

**Comment by yuxitong** [comment]
我就是这个行业的，这个目前叫DSM  主动安全预警系统。我并不能把我们公司训练好的模型给你，这个demo里 有我们最早训练的版本 虽然准确度不高，一切都要靠你们自己研究。

**Comment by wanghui6118942** [comment]
是这样子啊，那真的感谢您了！因为我们想用Python运行一下，但是看到您的demo是对应Android系统的，所以就不知道该怎么转换了。可以请教你下么？

**Comment by yuxitong** [comment]
我是android 开发人员   虽然 可以写python 但是不是很熟练   如果要完成你的需求 需要在网上查不少资料   所以抱歉了····   你也可以 百度 py如何调用摄像头 如何截图   至于 如何跑模型  我的自动打标里都有   你只需要  百度查到如何调用摄像头和截图就可以  我记得CV2可以做到

**Comment by wanghui6118942** [comment]
感谢您，祝您工作顺利。

**Comment by yuxitong** [comment]
thinks
