### ISSUE TITLE
请问作者哥哥或姐姐,输入图长和宽比例

### ISSUE THREAD

**Issue by logohoo** [yuxitong/TensorFlowDemo#14]
大哥或大姐姐你好。我下载了你关于骨架识别的文件，但是输入图片尺寸如果长和宽比例不一致，就无法获取，输出正确的数据，这个是为什么呢？我有QQ发了邮件，你告诉我这里问，我就这里问了，麻烦了，谢谢。

**Comment by yuxitong** [comment]
因为这个项目 输入和输出是有固定尺寸的
