### ISSUE TITLE
因为人体图，一般高>宽，如果两者一致的话，就造成输入数据的多余，增加运输量啊。graph_opt.pb 这个文件模型好像定死了一定要长和宽一致的图才可以有效识别，求解。多谢！

### ISSUE THREAD

**Issue by logohoo** [yuxitong/TensorFlowDemo#15]
因为人体图，一般高>宽，如果两者一致的话，就造成输入数据的多余，增加运输量啊。graph_opt.pb 这个文件模型好像定死了一定要长和宽一致的图才可以有效识别，求解。多谢！

**Comment by yuxitong** [comment]
诸如此类的模型 几乎都有定义 长和高  而且  绝大多数都是相等的··

**Comment by logohoo** [comment]
用了，耗时很严重啊，想修改下，训练模型的输入宽和高，问能否实现，谢谢？
