### ISSUE TITLE
打电话检测

### ISSUE THREAD

**Issue by hyh21521038** [yuxitong/TensorFlowDemo#17]
你好，请问你的打电话检测是采用什么方法处理的？直接用来分类吗？

**Comment by yuxitong** [comment]
不是分类  是ssd检测  object_detection

**Comment by hyh21521038** [comment]
> 不是分类 是ssd检测 object_detection
是直接检测手机和烟吗？手机的话有些角度会是一条线，这样会不会影响最后的效果？

**Comment by yuxitong** [comment]
会，但是你的检测 就只是单纯的靠模型检测出来 就算？  不后续写算法做过滤？

**Comment by hyh21521038** [comment]
如果做后处理，那也要能检测到才能做后处理。请问您这边是怎么处理手机一条线的情况的？

**Comment by yuxitong** [comment]
正常做报警啊··打标的时候 也直接打  具体还是得看你的业务       所有技术 都应该回归到使用   比如 你如果是视频检测 那么谁打电话会一动不动？  最后有露出来的情况吧？
