### ISSUE TITLE
有没有眨眼模型的训练集，感觉带眼镜效果不太好

### ISSUE THREAD

**Issue by happyhell** [yuxitong/TensorFlowDemo#18]

**Comment by yuxitong** [comment]
训练集 有 但是是公司的 没法外发~~~  恐怕你需要自己收集了····   你可以这样  先把这个模型上去 无论是误报还是正确的 都是可以用来做训练集的  这样逐渐的  训练集就越来越多了

**Comment by happyhell** [comment]
谢谢了，demo中提供的模型已经非常棒了。赞！！！
