### ISSUE TITLE
按照你们的经验，分类一张图片，大概需要多少毫秒？

### ISSUE THREAD

**Issue by happyhell** [yuxitong/TensorFlowDemo#19]
我用了几个方法，一种是saver.save 大概要800毫秒，saved model 需要30毫秒左右，如果直接用ckpt只要15毫秒，如何能够提高运行的效率呢？

**Comment by yuxitong** [comment]
用tflite啊  速度N倍~~~ TFLITE训练方式和这个是一样的

**Comment by happyhell** [comment]
我研究下，刚刚接触，很多都不懂，谢谢了

**Comment by yuxitong** [comment]
没事    tflite 速度超级快      等过段时间 如果有空我会上几个初始模型 ~~  不过可能要等年后咯

**Comment by happyhell** [comment]
节后我也试试，看看效果如何，我是在windows 上运行的，希望能更快些吧

**Comment by yuxitong** [comment]
windows啊·· 我实在 移动端上行
