### ISSUE TITLE
被墙以后手动下包的放置问题

### ISSUE THREAD

**Issue by butterl** [yuxitong/TensorFlowDemo#2]
新手问题啊，墙后面下不到部分的包，手工下完以后放置在哪呢，例如 ： tensorflow-android-1.4.0.aar 
方便共享下依赖文件在工程中的放置位置么?

**Comment by yuxitong** [comment]
这个下载完毕之后 是一个so包和jar包  你可以像其他程序一样引入！~ 在资产文件夹和libs文件夹里

**Comment by yuxitong** [comment]
<root url="file://$USER_HOME$/.gradle/caches/transforms-1/files-1.1/tensorflow-android-1.4.0.aar/6edc69be66320df94b5d65273f5e5f1e/res" />
      <root url="jar://$USER_HOME$/.gradle/caches/transforms-1/files-1.1/tensorflow-android-1.4.0.aar/6edc69be66320df94b5d65273f5e5f1e/jars/classes.jar!/" />


 这个是不是你要的位置？

**Comment by yuxitong** [comment]
你试试把你的aar文件放在libs里 然后在build.gradle 中的dependencies 里添加compile(name:'xxx',ext:'aar')  其中xxx是你下载的tensorflow-android-1.4.0  看看能否使用

**Comment by butterl** [comment]
lib里面需要hash做路径，我直接放到SDK的的目录下直接能找到

**Comment by yuxitong** [comment]
一般 aar的路径是在//$USER_HOME$/.gradle/caches/transforms-1/files-1.1/tensorflow-android-1.4.0.aar/这种地方
