### ISSUE TITLE
替换自己的模型

### ISSUE THREAD

**Issue by DRACOyu** [yuxitong/TensorFlowDemo#6]
我将自己的pb文件放入到asset目录下，同时修改了pb和txt文件，但是运行的时候直接闪退，请问我还需要改其他的吗

**Comment by yuxitong** [comment]
是这样的， 闪退的情况有很多种 。比如摄像头方向
但是 模型闪退的情况比较多
需要看具体报错，是tensorFlow版本不同训练出的模型无法跑也可能  还有可能是你的算法不兼容比如你把1的模型跑到2里面 那样 就会出数组越界错误

**Comment by DRACOyu** [comment]
我使用tensorflow1.5做的yolo2进行脸检测的，最后的输出是5*6，不是125

**Comment by yuxitong** [comment]
如果确定输出大小的话 直接修改model中的outputs大小就可以咯

**Comment by yuxitong** [comment]
实际上 骨架识别也是 输入和输出大小不对称的  你可以参考一下

**Comment by DRACOyu** [comment]
我已经将你的文件里的pb文件和网络的输入输出等都替换掉了，按理说是可以运行得了，请问我是不是还需要修改些其他的什么地方

**Comment by yuxitong** [comment]
正常情况下是可以的  但是 如果输入和输出有不同的话  比如不对称输入输出 那么就会有数组越界的报错   你看看是否有报错

**Comment by yizhiweimengxiangfendoudefeifei** [comment]
你好在吗可以回复一下吗
