### ISSUE TITLE
apk适用性问题

### ISSUE THREAD

**Issue by RayZhangSB** [yuxitong/TensorFlowDemo#9]
本想体验一下这个效果，我用的小米mix2s，但是进入里面4个功能都是黑屏后后退出。在其他手机上能正常运行？

**Comment by yuxitong** [comment]
有报错信息么？

**Comment by yizhiweimengxiangfendoudefeifei** [comment]
在吗?

**Comment by RayZhangSB** [comment]
真的抱歉，之前一致有事，没有报错信息的，就是黑屏后又回到主界面

**Comment by yuxitong** [comment]
你说的这种情况  黑屏回到主界面 是属于闪退了  应该会有报错日志吧！~   是android 8.0 么？  会不会是 没有给相机权限？   你手动给设备相机权限试一下

**Comment by RayZhangSB** [comment]
是8.0，给权限也跑不出来

**Comment by RayZhangSB** [comment]
报错日志在哪里看呢

**Comment by yuxitong** [comment]
在studio上可以看

**Comment by RayZhangSB** [comment]
之前只是用apk体验了下，今天为了解决在我的手机上无法使用的问题，我特地安装了下AS，然后加载库，出现了下面的问题:
![1](https://user-images.githubusercontent.com/33676127/47277202-41f14b80-d5f0-11e8-888c-7afcf6b6a5b2.png)
我看了一下版本不对应一致在报错，然而我的sdk下面并不存在26及以上的support的版本，感觉很奇怪你的app能编译通过

**Comment by yuxitong** [comment]
这个看不出什么问题   能否打开app  看看logcat里的报错？

**Comment by RayZhangSB** [comment]
好吧，上面那个版本问题已经解决，然后能成功导入手机了，现在导入之后还是跟你给的apk的结果一致但是AS上面没有报错信息

**Comment by RayZhangSB** [comment]
是不是需要在哪里调试一下，我看过了里面的文件现在没有任何一处有提示问题

**Comment by RayZhangSB** [comment]
我用的IDEA，不是ecilpse

**Comment by yuxitong** [comment]
IDEA我没用过 不太清楚  不过 android studio里有个logcat  我感觉 IDEA里应该也有  在这里吗 能看到 你点进去界面崩溃的错误
